// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1

package types

type OrderCreateReply struct {
	Code int `json:"code"`
}

type OrderCreateRequest struct {
	ProductID string `json:"product_id"`
}

type OrderReply struct {
	ID       string `json:"id"`
	State    uint32 `json:"state"`
	CreateAt string `json:"create_at"`
}

type OrderRequest struct {
	ID string `path:"id"`
}

type ProductReply struct {
	ID    int64   `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
	Count int64   `json:"count"`
}

type ProductRequest struct {
	ID int64 `path:"id"`
}

type RoleReply struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RoleRequest struct {
	ID string `path:"id"`
}

type UserAddReply struct {
	ID string `json:"id"`
}

type UserAddRequest struct {
	Name   string `json:"name"`
	Email  string `json:"email"`
	Mobile string `json:"mobile"`
	Avator string `json:"avator"`
}

type UserOrderRequest struct {
	ID string `path:"id"`
}

type UserOrdersReply struct {
	Orders []OrderReply `json:"orders"`
}

type UserReply struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Balance float64 `json:"balance"`
}

type UserRequest struct {
	ID string `path:"id"`
}
