// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1

package handler

import (
	"net/http"

	"mail/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: UserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id/orders",
				Handler: UserOrdersHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/order/:id",
				Handler: OrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: OrderCreateHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/product/:id",
				Handler: ProductHandler(serverCtx),
			},
		},
	)
}
